name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: fedora-latest  # Use Fedora latest runner environment

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v2  # Use setup-python@v2 for faster setup
      with:
        python-version: "3.12.3"

    - name: Cache pip and dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

  deploy:
    needs: build
    runs-on: fedora-latest
    steps:
      # Your deployment steps here
